name: angularattack2017
description: A web app for the angularattack2017 contest
version: 1.0.0
homepage: https://github.com/AndreiChernykh
author: Andrei Chernykh <a.d.chernykh@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular2: '>=2.2.0 <2.3.0'
  angular2_components: ^0.2.2
  less_dart: ^1.0.0

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.18+1

transformers:
- less_dart
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
